from enum import Enum

class AttemptState(str, Enum):
    INITIATED = "INITIATED"
    PENDING = "PENDING"
    BANK_SUCCESS = "BANK_SUCCESS"
    BANK_FAILED = "BANK_FAILED"
    GATEWAY_CONFIRMED = "GATEWAY_CONFIRMED"
    GATEWAY_FAILED = "GATEWAY_FAILED"
    TIMED_OUT = "TIMED_OUT"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"

class IntentState(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    POTENTIAL_DUPLICATE = "POTENTIAL_DUPLICATE"
    CONFLICTING_STATE = "CONFLICTING_STATE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class CorrelationRelation(str, Enum):
    RELATED = "RELATED"
    LIKELY_RELATED = "LIKELY_RELATED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNRELATED = "UNRELATED"

class ResolutionState(str, Enum):
    SAFE_TO_COMMIT = "SAFE_TO_COMMIT"
    HELD_FOR_REVIEW = "HELD_FOR_REVIEW"
    COMMITTED = "COMMITTED"
    REJECTED = "REJECTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    CONFLICTING_STATE = "CONFLICTING_STATE"

class RootCauseType(str, Enum):
    RC_NETWORK_TIMEOUT = "RC_NETWORK_TIMEOUT"
    RC_DUPLICATE_WEBHOOK = "RC_DUPLICATE_WEBHOOK"
    RC_DELAYED_WEBHOOK = "RC_DELAYED_WEBHOOK"
    RC_OUT_OF_ORDER = "RC_OUT_OF_ORDER"
    RC_CUSTOMER_RETRY = "RC_CUSTOMER_RETRY"
    RC_CONFLICTING_PROVIDER = "RC_CONFLICTING_PROVIDER"
    RC_MISSING_EVENT = "RC_MISSING_EVENT"
    RC_UNKNOWN = "RC_UNKNOWN"

class ReviewDecision(str, Enum):
    CONFIRM_ATTEMPT = "CONFIRM_ATTEMPT"
    MARK_DUPLICATE = "MARK_DUPLICATE"
