"""initial_schema

Revision ID: 879e582dd84f
Revises: 
Create Date: 2026-09-26 17:40:57.233142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879e582dd84f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregate_state', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'POTENTIAL_DUPLICATE', 'CONFLICTING_STATE', 'INSUFFICIENT_EVIDENCE', 'MANUAL_REVIEW', name='intentstate'), nullable=False),
    sa.Column('resolved_financial_transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_financial_transaction_id'], ['financial_transactions.id'], name='fk_payment_intents_transaction_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_aggregate_state'), 'payment_intents', ['aggregate_state'], unique=False)
    op.create_index(op.f('ix_payment_intents_customer_id'), 'payment_intents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_order_id'), 'payment_intents', ['order_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('generated_event_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_snapshot', sa.JSON(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_scenario_id'), 'simulation_runs', ['scenario_id'], unique=False)
    op.create_table('incident_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('root_cause_chain', sa.JSON(), nullable=False),
    sa.Column('correlation_evidence', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_analyses_intent_id'), 'incident_analyses', ['intent_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('merchant_session_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_sequence_hint', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('INITIATED', 'PENDING', 'BANK_SUCCESS', 'BANK_FAILED', 'GATEWAY_CONFIRMED', 'GATEWAY_FAILED', 'TIMED_OUT', 'CONFIRMED', 'FAILED', name='attemptstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_reference', name='uq_provider_reference')
    )
    op.create_index(op.f('ix_payment_attempts_intent_id'), 'payment_attempts', ['intent_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_provider'), 'payment_attempts', ['provider'], unique=False)
    op.create_index(op.f('ix_payment_attempts_provider_reference'), 'payment_attempts', ['provider_reference'], unique=False)
    op.create_table('financial_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('observed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('candidate_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('resolution_state', sa.Enum('SAFE_TO_COMMIT', 'HELD_FOR_REVIEW', 'COMMITTED', 'REJECTED', 'INSUFFICIENT_EVIDENCE', 'MANUAL_REVIEW', 'CONFLICTING_STATE', name='resolutionstate'), nullable=False),
    sa.Column('selected_attempt_id', sa.UUID(), nullable=True),
    sa.Column('candidate_attempt_ids', sa.JSON(), nullable=False),
    sa.Column('resolution_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ),
    sa.ForeignKeyConstraint(['selected_attempt_id'], ['payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_resolutions_intent_id'), 'financial_resolutions', ['intent_id'], unique=False)
    op.create_index(op.f('ix_financial_resolutions_resolution_state'), 'financial_resolutions', ['resolution_state'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', name='uq_financial_transaction_intent_id')
    )
    op.create_index(op.f('ix_financial_transactions_intent_id'), 'financial_transactions', ['intent_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_event_dedup_hash')
    )
    op.create_index(op.f('ix_payment_events_attempt_id'), 'payment_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_payment_events_dedup_hash'), 'payment_events', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_payment_events_event_created_at'), 'payment_events', ['event_created_at'], unique=False)
    op.create_index(op.f('ix_payment_events_event_received_at'), 'payment_events', ['event_received_at'], unique=False)
    op.create_index(op.f('ix_payment_events_provider'), 'payment_events', ['provider'], unique=False)
    op.create_table('transaction_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_attempt_id', sa.UUID(), nullable=False),
    sa.Column('target_attempt_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('RELATED', 'LIKELY_RELATED', 'INSUFFICIENT_EVIDENCE', 'UNRELATED', name='correlationrelation'), nullable=False),
    sa.Column('correlation_score', sa.Integer(), nullable=False),
    sa.Column('correlation_evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['target_attempt_id'], ['payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_links_source_attempt_id'), 'transaction_links', ['source_attempt_id'], unique=False)
    op.create_index(op.f('ix_transaction_links_target_attempt_id'), 'transaction_links', ['target_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_links_target_attempt_id'), table_name='transaction_links')
    op.drop_index(op.f('ix_transaction_links_source_attempt_id'), table_name='transaction_links')
    op.drop_table('transaction_links')
    op.drop_index(op.f('ix_payment_events_provider'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_received_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_created_at'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_dedup_hash'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_attempt_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_financial_transactions_intent_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_financial_resolutions_resolution_state'), table_name='financial_resolutions')
    op.drop_index(op.f('ix_financial_resolutions_intent_id'), table_name='financial_resolutions')
    op.drop_table('financial_resolutions')
    op.drop_index(op.f('ix_payment_attempts_provider_reference'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_provider'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_intent_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_incident_analyses_intent_id'), table_name='incident_analyses')
    op.drop_table('incident_analyses')
    op.drop_index(op.f('ix_simulation_runs_scenario_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_payment_intents_order_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_customer_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_aggregate_state'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
